[package]
name = "pos-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", features = ["macros", "json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
dotenvy = "0.15.7"

sea-orm = { version = "1.1.19", features = [
  "macros",
  "runtime-tokio-rustls",
  "sqlx-postgres",
  "with-uuid"
] }
bcrypt = "0.15"
jsonwebtoken = "9.3.0"
chrono = { version = "0.4.42", features = ["clock"] }
anyhow = "1.0.93"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-log = "0.2"
tracing-core = "0.1.35"
tower-http = { version = "0.6", features = ["trace"] }
bytes = "1.5"
http-body-util = "0.1"
async-trait = "0.1"